version: '3.1'

services:
  dev_app:
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
      args:
        - "APP_ENV"
        - "NEXT_PUBLIC_APP_VERSION"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - "APP_ENV=development"
      - "NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION"
    ports:
      - "3000:3000"
